### ISSUE TITLE
Failed to make.

### ISSUE THREAD

**Issue by radianthero** [crgimenes/internet_time#1]
clang -O3 -march=armv8-a -mtune=apple-m2 -flto -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -DNDEBUG -c main.c -o main.o
error: unknown target CPU 'armv8-a'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server, tigerlake, sapphirerapids, alderlake, raptorlake, meteorlake, sierraforest, grandridge, graniterapids, graniterapids-d, emeraldrapids, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, znver4, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
make: *** [Makefile:23: main.o] Error 1

**Comment by radianthero** [comment]
Doing it manually with `ggc -o internet_time main.c` still compiles fine.

**Comment by crgimenes** [comment]
I believe it is ok now.
Thanks for letting me know!
